server:
  port: 8001
  jetty:
    threads:
      acceptors: 5
      max: 300
      min: 50
      selectors: 5
      max-queue-capacity: 2000
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        http-only: true
      timeout: 15
      tracking-modes: COOKIE


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:multiplication
    username: sa
    password: sa
    hikari:
      connection-timeout: 10000
      max-lifetime: 10000
      maximum-pool-size: 70
      minimum-idle: 5000
      pool-name: multiplication-pool

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true